In [1]:
import numpy as np

In [2]:
#1
x = np.array([-1.6])

for j in range(0,100):
    A1 = x[j]-(x[j] * np.sin(3*x[j])-np.exp(x[j]))/ (np.sin(3*x[j])+3*x[j]*np.cos(3*x[j])-np.exp(x[j]))
    x = np.append(x, A1)
    fc = x[j]*np.sin(3*x[j])-np.exp(x[j])

    if abs(fc) < 1e-6:
        break

A1=x
A1

array([-1.6       ,  3.19799514,  2.46440244,  1.2035359 ,  0.65020146,
       -0.11692334, -0.66052349, -0.52192654, -0.56655274, -0.57074658,
       -0.57078962, -0.57078962])

In [3]:
np.shape(A1)

(12,)

In [10]:
xr = -0.4
xl = -0.7
A2 = []
for i in range(0, 100):
    xc = (xr+xl)/2
    A2.append(xc)
    fc = xc*np.sin(3*xc)-np.exp(xc)

    if fc > 0:
        xl = xc
    else:
        xr = xc

    if (abs(fc) < 1e-6):
        break

A2

[-0.55,
 -0.625,
 -0.5875,
 -0.5687500000000001,
 -0.578125,
 -0.5734375,
 -0.5710937500000001,
 -0.5699218750000001,
 -0.5705078125,
 -0.57080078125,
 -0.570654296875,
 -0.5707275390625,
 -0.57076416015625,
 -0.570782470703125,
 -0.5707916259765625,
 -0.5707870483398438,
 -0.5707893371582031]

In [5]:
A3 = np.array([j+1, i+1])
A3

array([11, 17])

In [6]:
#2
A = np.array([[1,2],[-1,1]])
B = np.array([[2,0],[0,2]])
C = np.array([[2,0,-3],[0,0,-1]])
D = np.array([[1,2],[2,3],[-1,0]])
x = np.array([1,0])
y = np.array([0,1])
z = np.array([1,2,-1])

In [7]:
A4 = A+B
A5 = 3*x - 4*y
A6 = np.dot(A,x)
x_minus_y = x-y
A7 = np.dot(B,x_minus_y)
A8 = np.dot(D,x)
A9 = np.dot(D,y)+z
A10 = np.dot(A,B)
A11 = np.dot(B,C)
A12 = np.dot(C,D)

display(A4)
display(A5)
display(A6)
display(A7)
display(A8)
display(A9)
display(A10)
display(A11)
display(A12)

array([[ 3,  2],
       [-1,  3]])

array([ 3, -4])

array([ 1, -1])

array([ 2, -2])

array([ 1,  2, -1])

array([ 3,  5, -1])

array([[ 2,  4],
       [-2,  2]])

array([[ 4,  0, -6],
       [ 0,  0, -2]])

array([[5, 4],
       [1, 0]])